#!/bin/sh /etc/rc.common

# --------------------------------------------------------------------
#
# Initial author: Zool Johan
# Created       : 11 Nov 2022
#
# Function      : mosquitto_sub to wait and collect data from ESP8266 whenever it publish and
#	   	          copy the final value to a file. 
#
# Run           : Run as OS service or nohup
#               : https://openwrt.org/docs/techref/initscripts
#               : https://openwrt.org/docs/guide-developer/procd-init-scripts
#
# --------------------------------------------------------------------

# Variables
START=99
STOP=00
NPID=$(ps | grep "[m]osquitto-subscribe.sh" | awk '{print $1}');

start() {

	if [ "$NPID" = "" ] ; then
		ash -c '/etc/collectd/mosquitto-subscribe.sh &'
	else
		echo "mosquitto-subscribe service is already running as $NPID";
	fi
	
}
 
stop() {

	ps | grep "[m]osquitto-sub.sh" | awk '{print $1}'
	for pid in $(ps | grep "[m]osquitto-subscribe.sh" | awk '{print $1}'); do kill -9 $pid; done
	
	ps | grep -E "[w]eather/duv|[w]eather/press|[w]eather/uv|[w]eather/presssea|[w]eather/humid|[w]eather/feelslike|[w]eather/alt|[w]eather/altreal|[w]eather/temperature2|[w]eather/temperature" | awk '{print $1}'
	for pid in $(ps | grep -E "[w]eather/duv|[w]eather/press|[w]eather/uv|[w]eather/presssea|[w]eather/humid|[w]eather/feelslike|[w]eather/alt|[w]eather/altreal|[w]eather/temperature2|[w]eather/temperature" | awk '{print $1}'); do kill -9 $pid; done

}

#EOF