#!/bin/sh /etc/rc.common

# --------------------------------------------------------------------
#
# Initial author: Zool Johan
# Created	: 11 Nov 2022
#
# Function   	: mosquitto_sub to wait and collect data from ESP8266 whenever it publish and 
#	   	  copy the final value to a file. 
# 
# Run 		: Run as OS service or nohup
#		: https://openwrt.org/docs/techref/initscripts
# 
# --------------------------------------------------------------------

# Variables
START=99
STOP=00
PATH_COLLECTD="/etc/collectd"

main() {
	echo "$(date) start main" >> $PATH_COLLECTD/status.txt
	nohup $PATH_COLLECTD/mosquitto-subscribe.sh 1>>$PATH_COLLECTD/status.txt 2>>$PATH_COLLECTD/status.txt &
}

start() {
        echo "$(date) start" >> $PATH_COLLECTD/status.txt
	main
}                 
 
stop() {
	ps | grep "[m]osquitto-sub" | awk '{printf " " $1}'
	for pid in $(ps | grep "[m]osquitto-sub" | awk '{print $1}'); do kill -9 $pid; done
	echo "$(date) stop" >> $PATH_COLLECTD/status.txt
	
	ps | grep "[m]osquitto_sub" | awk '{printf " " $1}'
	for pid in $(ps | grep "[m]osquitto_sub" | awk '{print $1}'); do kill -9 $pid; done
	echo "$(date) stop" >> $PATH_COLLECTD/status.txt
}
